- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/0/{00000..00011}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/1/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/2/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/3/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/4/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/5/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/6/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/7/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/8/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/9/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/10/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/11/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/12/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/13/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/14/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/15/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/16/{00000..00001}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/17/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/18/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/19/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/20/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/21/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/22/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/23/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/24/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/25/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/26/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/27/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/28/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/29/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/30/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/31/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/32/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/33/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/34/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/35/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/36/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/37/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/38/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/39/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/40/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/41/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/42/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/43/{00000..00021}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/44/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/45/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/46/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/47/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/48/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/49/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/50/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/51/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/52/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/53/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/54/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/55/{00000..00019}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/56/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/57/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/58/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/59/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/60/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/61/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/62/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/63/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/64/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/65/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/66/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/67/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/68/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/69/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/70/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/71/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/72/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/73/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/74/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/75/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/76/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/77/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/78/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/79/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/80/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/81/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/82/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/83/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/84/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/85/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/86/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/87/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/88/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/89/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/90/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/91/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/92/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/93/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/94/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/95/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/96/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/97/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/98/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/99/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/100/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/101/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/102/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/103/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/104/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/105/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/106/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/107/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/108/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/109/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/110/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/111/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/112/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/113/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/114/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/115/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/116/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/117/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/118/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/119/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/121/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/122/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/123/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/124/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/125/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/126/{00000..00020}.tar -"
- "pipe:aws s3 cp s3://muse-datasets/sdxl-synthetic-dataset/127/{00000..00020}.tar -"
